name: Workflow B

on:
  workflow_run:
    workflows: [Workflow A]
    types:
      - completed

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Hello from Workflow B"
          echo "Workflow ID: ${{ github.event.workflow_run.workflow_id }}"
          echo "Head Branch: ${{ github.event.head_branch }}"
          